### ISSUE TITLE
$echo with no arguments

### ISSUE THREAD

**Issue by ct-bess** [MichaelHHall/liberty#1]
The `$echo` command is spectacular, however it lacks flexibility. For instance, if a user submits an `$echo` with no arguments, there is nothing for Liberty to consume; Thus the command ends right then and there. I propose, that we allow the user the option to give no arguments!

## Context

I know two bots that have functionality that lets an `echo` command use zero arguments. What these bots do, is if there's no arguments, they use the message before the `echo` command as the arguments. So, the `echo` command called with no arguments actually consumes the *n-1*th message as it's arguments.

## Expected Results

Liberty Prime consumes the *n-1*th message in the channel cache as the `echo` command's arguments when the user gives no arguments for this command. Else, Liberty Prime uses the supplied arguments as usual.

For example: `$echo hello world` produces `hello world`
But then saying: `$echo` will produce `hello world` as well assuming the previous message in the channel was Liberty Prime's previous response.

## Current Results

Liberty Prime provides no response what so ever; In fact, you could say, Liberty Prime is ignoring an echo command entirely if it's invoked with no arguments.

For example: `$echo` produces nothing

## Possible Fix

I'm no Liberty wizard, but I'm guessing that the `echo_message` function is not being called because `msg` isn't being supplied when it's `null`. So yeah turns out I have no idea how any of this gets magically mapped through the Discord Python API or what ever yea nice ok have a nice day

https://github.com/MichaelHHall/liberty/blob/e0aeaebf3ee16fc4d4904273b832a7daca54af82/liberty/commands/text.py#L13-L15

### edit
it's *n-1* not *n-2* oops
> *n* is the command, *n-1* is the message above the command

**Comment by MichaelHHall** [comment]
Fixed by [742db42](https://github.com/MichaelHHall/liberty/commit/742db425f13d5f1fbb960b16b4ffc5b22463aa3e)
